### ISSUE TITLE
Refactor some configuration files

### ISSUE THREAD

**Issue by nachoogriis** [taed2-2425q1-gced-upc/TAED2_YOLOs#9]
### What

At the moment some configuration files have absolute paths that are defined for a single computer. We could just store those paths in `.env` files so everyone can adapt it to their needs.

### How

Add to the personal `.env` file something like `BASE_FOLDER` and refactor the configuration files to adapt them to this change.

**Comment by nachoogriis** [comment]
This has been partially solved in this [PR](https://github.com/taed2-2425q1-gced-upc/TAED2_YOLOs/pull/13). However, there are still some config files spread over the repo. We should consider unifying all this into the config file into the person_image_segmentation config file once everything else is implemented

**Comment by marcjaner** [comment]
Good point, a single `config` file would make things way easier. And still, we should aim to have all settings that need to change based on the user stored as environmental variables

**Comment by nachoogriis** [comment]
This has been closed in the following Pull Request #22
